version: "3.8"

services:
  api_aplicacoes_internas:
    image: api_aplicacoes_internas:v0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - traefik_public
        #ports:
        #- "3000:80"
        #- "3000:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.api_aplicacoes_internas.rule=Host(`api-aplicacoes-internas.usekingjoe.com.br`)"
        - "traefik.http.routers.api_aplicacoes_internas.entrypoints=websecure"
        - "traefik.http.routers.api_aplicacoes_internas.priority=1"
        - "traefik.http.routers.api_aplicacoes_internas.tls.certresolver=le"
        - "traefik.http.routers.api_aplicacoes_internas.service=api_aplicacoes_internas"
        - "traefik.http.services.api_aplicacoes_internas.loadbalancer.server.port=8000"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

